export const myExperiance = [
  { technology: "HTML", level: "Experienced" },
  { technology: "CSS", level: "Experienced" },
  { technology: "SaaS", level: "Experienced" },
  { technology: "JavaScript", level: "Experienced" },
  { technology: "TypeScript", level: "Experienced" },
  { technology: "React Js", level: "Experienced" },
  { technology: "Redux", level: "Experienced" },
  { technology: "Material Ui", level: "Experienced" },
  { technology: "Shopify Polaris", level: "Experienced" },
  { technology: "Ant Design", level: "Experienced" },
  { technology: "Tailwind Css", level: "Experienced" },
  { technology: "Bootstrap", level: "Experienced" },
  { technology: "Storybook", level: "Experienced" },
  // { technology: "Node Js", level: "Beginner", type: "backend" },
  { technology: "Php", level: "Intermediate", type: "backend" },
  // { technology: "Java", level: "Intermediate", type: "backend" },
  { technology: "MySql", level: "Intermediate", type: "backend" },
];
